### ISSUE TITLE
Matcher / transform command line tool

### ISSUE THREAD

**Issue by kstaken** [terascope/alerting-assets#5]
In order to make it easier to test a matcher / transform configuration it would be helpful to have simple command line tools that allow you to provide your list of rules and set of sample data then simply apply the rules to the sample data and gives you the output. 

This tool should be part of the node.js package for the transform / matcher library and should be installable when the library is installed.

BTW, I think the library should be named something like `ts-transform` and we define matching as  a highly simplistic form of transform.

To start I think it just needs to be pretty simple. Maybe two different commands.

```
ts-transform input.json rules.json
```

And then maybe 

```
ts-match input.json [rules.json | rules.txt] 
```

On `ts-match` if the input is json it would expect one JSON per line. These could be transform rules or they could just be rules with only a selector like this. 

```
{ selector: "myfield:value" }
{ selector: "myfield2:value2" }
```

Whether you get this or full transform rules the behavior would be the same. For transforms it would just apply the selection phase.

If it's a text input then it would just be one selector per line.

```
myfield:value
myfield2:value2
```

Obviously, none of this is really command line specific, the library should support this in general and the command line just wraps the existing functionality.

**Comment by jsnoble** [comment]
this has been implemented in the library ts-transforms
